# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"

  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  sudo apt-get update

  sudo apt-get install linux-image-generic-lts-raring linux-headers-generic-lts-raring

  sudo reboot

  sudo sh -c "curl https://get.docker.io/gpg | apt-key add -"

  sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

  sudo apt-get update

  sudo apt-get install lxc-docker


end
